import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import { ClerkProvider } from "@clerk/nextjs";

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UniPrep",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

<ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />

      </body>
    </html>
</ClerkProvider>
    
  );
}
